# Generated by Django 5.1.1 on 2024-11-05 04:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], max_length=30)),
                ('debt', models.DecimalField(decimal_places=10, max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_payments', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed')], max_length=30)),
                ('value_delayed', models.DecimalField(decimal_places=10, max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.credit')),
            ],
        ),
    ]
