# Generated by Django 5.1.1 on 2024-11-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('address', models.CharField(max_length=255, verbose_name='home address')),
                ('phone', models.CharField(max_length=255, verbose_name='phone number')),
            ],
        ),
    ]
