# Generated by Django 5.1.1 on 2024-10-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('address', models.CharField(max_length=255, verbose_name='home address')),
                ('phone', models.CharField(max_length=255, verbose_name='phone number')),
            ],
        ),
    ]
